name: Check/Format PR

on:
  pull_request:
    branches: [ master ]

jobs:
  format:
    name: Format PR
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Install goimports
        run: |
          go mod download golang.org/x/tools
          go install golang.org/x/tools/cmd/goimports
      - name: Format repo
        run: |
          ./format_repo.sh
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          CHANGE_TARGET: ${{ github.base_ref }}
      - name: Changes detected
        id: detect-changes
        run: |
          changes=$(git status --porcelain)
          if [ ! -z "$changes" ]; then
             echo "::set-output name=has-changes::true"
          fi
      - uses: EndBug/add-and-commit@v7
        if: ${{ steps.detect-changes.outputs.has-changes == 'true' }}
        with:
          message: "[ga-format-pr] Run ./format_repo.sh to fix formatting"
          add: "."
          cwd: "."
  verify:
    needs: format
    name: Verify format
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Check all
        id: check_format
        run: |
          ./check_repo.sh
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          CHANGE_TARGET: ${{ github.base_ref }}
